source 'https://cdn.cocoapods.org/'

target 'JSBadgeView', :exclusive => true do
  pod "JSBadgeView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JSBadgeView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
